In [3]:
import numpy as np
from random import randint , random
import scipy as sp

a = np.ones((10, 10))
a1 = np.zeros((10, 10))
a2 = np.full((10,10),10)
a3 = np.eye(10)
a4 = np.empty((10,10)) # 10x10 empity matrix


# Arrange [start , end) it does not include the end
b = np.arange(10) # deafult step is 1 
b1 = np.arange(10, 20 , 2) # start , end , step

#  lines space [start , end] it does include the end
c = np.linspace(10, 20, 11) # 11 elements starting from 10 to 20


d = np.random.rand(2,2) # 2x2 random matrix elements bn [0,1)
d1 = np.random.randint(2, 5,size=(3,4)) # 3x4 random matrix elements b/n [2,5)

print(d)
print(d1)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)
# print(a.astype(int))
# print(a.dtype.name)


# x = np.array([1,2,3])
# y = np.array(([1.5,7,3],[4,5,6]))

# y.max

[[0.60208202 0.97913877]
 [0.61142455 0.99832789]]
[[2 4 2 3]
 [3 2 4 2]
 [3 3 2 3]]


Array manipulations

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

b = np.append(a, [[7,8,9]], axis=0)  # add row wise 

c = np.append(a, [[7],[10]], axis = 1) # add column wise

print("append row Wise")
print(b)
print("append Col Wise")
print(c)


d=np.resize(a,(4,6))
print(a)

a = np.array([[1,2,3],[4,5,6]])

b = np.concatenate((a, [[7,8,9]]), axis=0)  # add row wise 

c = np.concatenate((a, [[7],[10]]), axis = 1) # add column wise

print("Add row Wise")
print(b)
print("Add Col Wise")
print(c)


a = np.array([[1,2,3],[4,5,6]])

b = np.vstack((a, [[7,8,9]]))  # add row wise 

c = np.hstack((a, [[7,8],[10,11]])) # add column wise

print("Add row Wise")
print(b)
print("Add Col Wise")
print(c)

h = np.array([4,5,6])
g = np.array([[ a , h]])
print(g)



Splliting : Creates Lis of Numpy arrays

In [ ]:
print("colomon wise spliition")
print(np.hsplit(a,3))
print(np.split(a,3,axis=1))

print("Row  wise spliition")
print(np.vsplit(a,2)) 
print(np.split(a,2,axis=0))

Slicing 

In [ ]:
x = np.array([1,2,3])

print(x[ np.array([-3])]) # index number to filter 

print(x[ [1,2]]) # list of index numbers 
 

y = np.array([[1,2,3],[4,5,6]])

print(y[ [0,1] ,[0,1]])  # y [ [rows ] , [columns ] ] list of rows and columns 


z = y[y>1]
print(z)

In [ ]:
# J_v_x  = np.block)

# print(J_v_x)
# zk = []
np.block( [[np.zeros((3,3)), np.ones((3,2))] , [np.ones((2,2)), np.zeros((2,3))]])

# zk.append(  [1],[2])
# print(zk)
# zk.append([1],[2])
# print(zk)
Rf = np.zeros((0,0))
Rfc = np.diag(np.array([0.25 ** 2,0.5 ** 2])) 
# print(Rfc)

a =np.array([1,2])
b=np.array([3,4])

# Rf = np.block([ [Rf] ,[ b]])
# Rf.append(Rfc)
Rf = sp.linalg.block_diag(Rf,Rfc)

print(Rf)
Rf = sp.linalg.block_diag(Rf,Rfc)
print(Rf)
# print(Rf)

In [69]:

xk  =  np.array([ ['x'], ['y'], ['z']]) # 3x1

XK = xk  # intialize using only robot pose

PK = np.diag([1,1,1]) # 3x3 array 

print(PK)
NF1 = np.array([['nf1x'],['nf1y']])  # xk + ( zf + vk )

pf1 = np.diag( [0.5,0.5]) # 2x2 array 

BF2 = np.array([['bf2x'],['bf2y']])

pf2 = np.diag( [0.5,0.5]) # 2z2 array 


XK = np.block([ [XK],[NF1]])
print(XK)


pose_dim = 3
pre_dim = len(XK) - len(NF1)


# gx = np.full((len(BF2),pose_dim) , 1)  # jacobian g with respect to pose

# gv = np.full((len(BF2),len(BF2)), 2)  # jacobian gv with respect to noise 

# G1 = np.block([[np.eye(pre_dim)],[gx]])
 
# G2 = np.block([[np.zeros((pre_dim , len(NF1)))],[gv]])

# print("Jacobian G1")
# print(G1)
# print("Jacobian G2")
# print(G2)
# PK = G1@PK@G1.T 

# RF = G2@pf1@G2.T

# print("New PF")
# print(PK)

# print("New RF:")
# print(RF)

# TOT_PF =PK + RF 
# print("PF ")
# print(TOT_PF)

# Add Feature From World Frame 

PK= np.eye((pose_dim+len(NF1)))

XK = np.block([ [XK],[BF2]])
# print(XK ,PF)


pre_dim = len(XK) - len(BF2)


gx = np.full((len(BF2),pose_dim) , 3)  # jacobian g with respect to pose

gv = np.full((len(BF2),len(BF2)), 4)  # jacobian gv with respect to noise 

G1 = np.block([[np.eye(pre_dim)]  , [gx,np.zeros((len(BF2), pre_dim-pose_dim)) ]])
print(G1)


G2 = np.block([[np.zeros((pre_dim , len(BF2)))],[gv]])

print("Jacobian G1")
print(G1)
print("Jacobian G2")
print(G2)
PK = G1@PK@G1.T 

RF = G2@pf1@G2.T

print("New PF")
print(PK)

print("New RF:")
print(RF)

TOT_PF =PK + RF 
print("PF ")
print(TOT_PF)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[['x']
 ['y']
 ['z']
 ['nf1x']
 ['nf1y']]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [3. 3. 3. 0. 0.]
 [3. 3. 3. 0. 0.]]
Jacobian G1
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [3. 3. 3. 0. 0.]
 [3. 3. 3. 0. 0.]]
Jacobian G2
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [4. 4.]
 [4. 4.]]
New PF
[[ 1.  0.  0.  0.  0.  3.  3.]
 [ 0.  1.  0.  0.  0.  3.  3.]
 [ 0.  0.  1.  0.  0.  3.  3.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 3.  3.  3.  0.  0. 27. 27.]
 [ 3.  3.  3.  0.  0. 27. 27.]]
New RF:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 16. 16.]
 [ 0.  0.  0.  0.  0. 16. 16.]]
PF 
[[ 1.  0.  0.  0.  0.  3.  3.]
 [ 0.  1.  0.  0.  0.  3.  3.]
 [ 0.  0.  1.  0.  0.  3.  3.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.

In [91]:
# Add New Uncertinity to Pk
feature_dim = 2
Pk= np.eye(10)
pose_dim =3
Jgx = np.full((3,3), 1)  #
# print(PK)
# print(PK[0:3,0:3])

End = Jgx@(PK[0:pose_dim,0:pose_dim]) @ Jgx.T  # end digonal matrix 

Lower_block = Jgx@(Pk[0:pose_dim,0:pose_dim])  # 

Right_block = (Pk[0:pose_dim,0:pose_dim]) @ Jgx.T

for i in range(pose_dim , len(Pk) , feature_dim):
    
    Lower = Jgx@PK[0 : pose_dim, i:i+feature_dim]
    Right = Pk[i:i+feature_dim,0:pose_dim] @ Jgx.T

    Lower_block = np.block([[Lower_block , Lower]])
    Right_block = np.block([[Right_block] , [Right]])


Pk_plus = np.block([[Pk,Right_block],[Lower_block,End]])


Pk_robot

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3.]]


In [15]:
import numpy as np
import scipy as sp


znp = np.array([[1],[1],[2],[2]])

Rfc = np.diag(np.array([0.25 ** 2,0.5 ** 2])) 
Rnp = np.zeros((0,0))
for i in range(int(len(znp)/2)):
    Rnp= sp.linalg.block_diag(Rnp,Rfc)


x0 = np.zeros((3, 1))
P0 = np.zeros((3, 3))

x0 = np.block([[x0],[znp]])

P0 = sp.linalg.block_diag(P0,Rnp)

print("new x0")
print(x0)

print("new P0")
print(P0)

new x0
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [2.]
 [2.]]
new P0
[[0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.0625 0.     0.     0.    ]
 [0.     0.     0.     0.     0.25   0.     0.    ]
 [0.     0.     0.     0.     0.     0.0625 0.    ]
 [0.     0.     0.     0.     0.     0.     0.25  ]]
